export default {
  nobinNT: require('../assets/nobin-nt.png'),
  fogoNT: require('../assets/fogo-nt.png'),
  glassNT: require('../assets/glass-nt.png'),
  recyclingNT: require('../assets/recycling-nt.png'),
  rubbishNT: require('../assets/rubbish-nt.png'),
  fogo: require('../assets/fogo.png'),
  glass: require('../assets/glass.png'),
  recycling: require('../assets/recycling.png'),
  rubbish: require('../assets/rubbish.png'),
  hbccLogo: require('../assets/hbcc-logo.png'),
  recyclingLogo: require('../assets/recycling-20-logo.png'),
  r2Bins: require('../assets/r2_bins.png'),
  r2BinSearch: require('../assets/r20_item_search.png'),
  recyclingLogoStretch: require('../assets/recycling-20-logo-stretch.png'),
  recyclingLogoWite: require('../assets/recycling-logo-white.png'),
  aerielAltona: require('../assets/aeriel-altona.png'),
  custService:  require('../assets/Call-Customer-service.png'),
  langLine: require('../assets/Language-Line.png'),
  liveChat: require('../assets/Live-chat.png'),
  relayService: require('../assets/National-Relay-Service.png'),
  visit:  require('../assets/Visit.png'),
};
